apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: customer-server
  template:
    metadata:
      labels:
        component: customer-server
    spec:
      containers:
        - name: customer-server
          image: varunchandrashekar1/customer-server-593-594-606-607:latest
          ports: 
            - containerPort: 8001
          env:
            - name: PORT
              value: "8001"
            - name: DB_SERVER
              value: "http://database-server-cluster-ip-service:8080"
            - name: STORE_SERVER
              value: "http://store-server-cluster-ip-service:8000"
            - name: PRODUCTS_SERVER
              value: "http://products-server-cluster-ip-service:8002"
            - name: JWT_SECRET
              value: "rm2dDQL1A7gkenleDlX1FmFAMMiLUhCGSnpwdaWnzGc="
