apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: store-server
  template:
    metadata:
      labels:
        component: store-server
    spec:
      containers:
        - name: store-server
          image: [DOCKER_ID]/store-server-593-594-606-607
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
