apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: store-server
  template:
    metadata:
      labels:
        component: store-server
    spec:
      containers:
        - name: store-server
          image: varunchandrashekar1/store-server-593-594-606-607:latest
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
            - name: DB_SERVER
              value: "http://database-server-cluster-ip-service:8080"
            - name: CUSTOMER_SERVER
              value: "http://customer-server-cluster-ip-service:8001"
            - name: PRODUCTS_SERVER
              value: "http://products-server-cluster-ip-service:8000"
            - name: JWT_SECRET
              value: "rm2dDQL1A7gkenleDlX1FmFAMMiLUhCGSnpwdaWnzGc="
