pipeline {
    environment {
        customerImage   = ''
        productImage    = ''
        storeImage      = ''
        databaseImage   = ''
        customermicroservice    = 'varunchandrashekar1/customer-server-593-594-606-607'
        productmicroservice     = 'varunchandrashekar1/products-server-593-594-606-607'
        storemicroservice       = 'varunchandrashekar1/store-server-593-594-606-607'
        databasemicroservice    = 'varunchandrashekar1/database-server-593-594-606-607'

    }

    agent any

    stages {
        stage("testing stageJenkins"){
            steps {
                echo 'jenkins running'
            }
        }
        stage('Checkout Source') {
            steps {
                git branch: 'main', url: 'https://github.com/Vaarun-Kamath/E-Commerce-Microservices.git'
                sh 'echo "git clone completed"'
                sh 'dir'
            }
        }
        stage('client izer') {
            steps {
                // dir('../client') {
                script {
                    sh 'dir'
                    sh 'ls'
                    sh 'npm run dev'
                }
                // }
            }
        }
        // stage('Build Images') {
        //     steps {
        //         dir('customer-server-593-594-606-607') {
        //             script {
        //                 customerImage = docker.build customermicroservice
        //             }
        //         }
        //         dir('product-server-593-594-606-607') {
        //             script {
        //                 productImage = docker.build productmicroservice
        //             }
        //         }
        //         dir('store-server-593-594-606-607') {
        //             script {
        //                 storeImage = docker.build storemicroservice
        //             }
        //         }
        //         dir('database-server-593-594-606-607') {
        //             script {
        //                 databaseImage = docker.build storemicroservice
        //             }
        //         }
        //     }
        // }
        // stage('Push Images') {
        //     steps {
        //         script {
        //             docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
        //                 orderImage.push()
        //                 productImage.push()
        //                 userImage.push()
        //             }
        //         }
        //     }
        // }

        // stage('List pods') {
        //     steps{
        //         sh 'curl -LO "https://storage.googleapis.com/kubernetes-release/release/v1.20.5/bin/linux/amd64/kubectl"'
        //         sh 'chmod u+x ./kubectl'
        //     }
        // }

        // stage('Deploy kubernetes') {
        //     steps {
        //         sh './kubectl apply -f ./k8s'
        //     }
        // }
        
        stage('test') {
            steps {
                echo 'to test'
            }
        }
    }
}
